//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpmg.Messages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kpmg.Messages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KPMG Coding test.
        /// </summary>
        public static string Application_Footer {
            get {
                return ResourceManager.GetString("Application_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KPMG Coding test.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload.
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload a CSV.
        /// </summary>
        public static string Index_Update_CSV {
            get {
                return ResourceManager.GetString("Index_Update_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload a CSV file by clicking ont the button below.
        /// </summary>
        public static string Index_Update_CSV_Text {
            get {
                return ResourceManager.GetString("Index_Update_CSV_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload an XLSX.
        /// </summary>
        public static string Index_Update_XLSX {
            get {
                return ResourceManager.GetString("Index_Update_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload a XLSX file by clicking ont the button below.
        /// </summary>
        public static string Index_Update_XLSX_Text {
            get {
                return ResourceManager.GetString("Index_Update_XLSX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show all.
        /// </summary>
        public static string Menu_AllDatas {
            get {
                return ResourceManager.GetString("Menu_AllDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload a file.
        /// </summary>
        public static string Menu_Upload {
            get {
                return ResourceManager.GetString("Menu_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of datas.
        /// </summary>
        public static string ShowAll_Title {
            get {
                return ResourceManager.GetString("ShowAll_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line.
        /// </summary>
        public static string Upload_Column_Line {
            get {
                return ResourceManager.GetString("Upload_Column_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can upload an XLSX or CSV file to calculate your taxes.
        /// </summary>
        public static string Upload_Message {
            get {
                return ResourceManager.GetString("Upload_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload a file.
        /// </summary>
        public static string Upload_Title {
            get {
                return ResourceManager.GetString("Upload_Title", resourceCulture);
            }
        }
    }
}
